# Generated by Django 6.0.2 on 2026-02-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dori nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price', models.IntegerField(verbose_name="Narxi (so'm)")),
                ('image', models.ImageField(upload_to='medicines/', verbose_name='Rasmi')),
            ],
        ),
    ]
